server:
  port: 11012
  name: "eventmesh-workflow"
flow:
  queue:
    store: in-memory
  schedule:
    interval: 500 # milliseconds
plugins:
  registry:
    nacos:
      address_list: "9.135.90.236:8848"
  selector:
    nacos:
      address_list: "9.135.90.236:8848"
  database:
    mysql:
      dsn: "root:123456@(127.0.0.1:3306)/db_workflow?charset=utf8&parseTime=True&loc=Local"
      max_idle: 50
      max_open: 100
      max_lifetime: 180000
  log:
    default:
      - writer: console
        level: debug
      - writer: file
        level: info
        writer_config:
          filename: ./workflow.log
          max_size: 10
          max_backups: 10
          max_age: 7
          compress:  false
    schedule:
      - writer: console
        level: debug
      - writer: file
        level: info
        writer_config:
          filename: ./workflow_schedule.log
          max_size: 10
          max_backups: 10
          max_age: 7
          compress:  false
    queue:
      - writer: console
        level: debug
      - writer: file
        level: info
        writer_config:
          filename: ./workflow_queue.log
          max_size: 10
          max_backups: 10
          max_age: 7
          compress:  false
